services:
  - type: web
    name: n8n
    env: docker
    
    # ---- THIS IS THE KEY CHANGE ----
    # This tells Render to build the Dockerfile in your repository's root directory
    # instead of pulling a pre-built image from Docker Hub.
    dockerfilePath: ./Dockerfile
    dockerContext: .
    # --------------------------------

    disk:
      name: n8n-data
      mountPath: /data
      sizeGB: 10
    envVars:
      # These variables are still useful to set here as they are specific
      # to your Render environment (like the hostname).
      - key: N8N_HOST
        value: n8n-ffmpeg-deploy-tkgq.onrender.com
      - key: N8N_PROTOCOL
        value: https
      - key: WEBHOOK_URL
        value: https://n8n-ffmpeg-deploy-tkgq.onrender.com/
      - key: N8N_ENCRYPTION_KEY # Keep this for security
        generateValue: true
      - key: N8N_BLOCK_ENV_ACCESS_IN_NODE
        value: "false" # Overrides the Dockerfile ENV for your specific need

    autoDeploy: true
